# NumPy 

In [48]:
import numpy as np

## 文件的输入输出

In [79]:
# 文件的输入输出
arr = np.arange(10)
np.save('output/some_array', arr)
np.load('output/some_array.npy')

np.savez('output/array_archive.npz', a=arr, b=np.arange(20))
arch = np.load('output/array_archive.npz')
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

读写各种格式的文件：

文件格式|使用的包|函数
----|----|----
txt | numpy | loadtxt, genfromtxt, fromfile, savetxt, tofile
csv | csv | reader, writer
Matlab | scipy.io | loadmat, savemat
hdf | pytables, h5py| 
NetCDF | netCDF4, scipy.io.netcdf | netCDF4.Dataset, scipy.io.netcdf.netcdf_file
**文件格式**|**使用的包**|**备注**
wav | scipy.io.wavfile | 音频文件
jpeg,png,...| PIL, scipy.misc.pilutil | 图像文件
fits | pyfits | 天文图像

## 生成array对象

与列表不同，数组中要求所有元素的 `dtype` 是一样的，如果传入参数的类型与数组类型不一样，需要按照已有的类型进行转换。

In [1]:
# list 转array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# 设置数据类型
data2 = [[1,2,3, 4], [5, 6, 7,8]]
arr2 = np.array(data2, dtype=np.int32)
arr2.dtype

dtype('int32')

In [5]:
# 基本属性
print(arr1.ndim,arr1.shape,arr1.dtype)

1 (5,) float64


In [7]:
# 生成连续的range值
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# 将输入转为array
np.asarray([1,2])

array([1, 2])

In [18]:
# 生成二维的array
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr2d)
arr2d[0,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

## 数组形态的改变

### transpose：转置 

使用 `transpose` 返回数组的转置，本质上是将所有维度反过来：

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

注意：
- 对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置
- 转置可以作用于多维数组
- 转置只是交换了轴的位置。
- 转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。

### reshape:数组重塑

In [53]:
# 改变arr 的形状
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [54]:
#－1表示维度大小由数据本身推断
arr = np.arange(12)
arr.reshape((3,4)).reshape((6,2))
arr.reshape((4,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### ravel,flatten,flat:数组展开

In [29]:
# 相反操作：扁平化和散开
arr = np.arange(15).reshape((5,3))
print(arr)
arr.ravel()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
#列优先
arr = np.arange(12).reshape((3,4))
print(arr)
arr.ravel('F')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [31]:
# flatten
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

`flat` 相当于返回了所有元组组成的一个迭代器：

In [32]:
arr.flat

### concatenate,split:数组合并与拆分

In [61]:
#数组的合并
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
# 数组的拆分
# split(ary, indices_or_sections, axis=0) 
# 把一个数组从左到右按顺序切分 
# 参数： 
# ary:要切分的数组 
# indices_or_sections:如果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置 
# axis：沿着哪个维度进行切向，默认为0，横向切分

np.random.seed(9)
arr = np.random.randn(5,2)
print(arr,'\n ##########')
f,s,t = np.split(arr, [1,3])
print(f,'\n ##########')
print(s,'\n ##########')
print(t,'\n ##########')

[[ 1.10855471e-03 -2.89544069e-01]
 [-1.11606630e+00 -1.28827567e-02]
 [-3.78361464e-01 -4.81135363e-01]
 [-1.51733118e+00 -4.90871981e-01]
 [-2.40680579e-01 -6.47947460e-01]] 
 ##########
[[ 0.00110855 -0.28954407]] 
 ##########
[[-1.1160663  -0.01288276]
 [-0.37836146 -0.48113536]] 
 ##########
[[-1.51733118 -0.49087198]
 [-0.24068058 -0.64794746]] 
 ##########


### repeat,tile:元素的重复扩展

In [77]:
# repeat 以行/列为单位进行指定倍数扩展
arr = np.arange(3)
print(arr.repeat(3))
print(arr.repeat([2,3,4]))

[0 0 0 1 1 1 2 2 2]
[0 0 1 1 1 2 2 2 2]


In [76]:
# 二维array的扩展
np.random.seed(34)
arr = np.random.randn(2,2)
print(arr,'\n ##########')
print(arr.repeat(2, axis=0),'\n ##########')
print(arr.repeat([2,3], axis=0),'\n ##########')
print(arr.repeat([2,3], axis=1),'\n ##########')

[[ 0.2438351  -0.74731818]
 [-1.56117699 -0.46425312]] 
 ##########
[[ 0.2438351  -0.74731818]
 [ 0.2438351  -0.74731818]
 [-1.56117699 -0.46425312]
 [-1.56117699 -0.46425312]] 
 ##########
[[ 0.2438351  -0.74731818]
 [ 0.2438351  -0.74731818]
 [-1.56117699 -0.46425312]
 [-1.56117699 -0.46425312]
 [-1.56117699 -0.46425312]] 
 ##########
[[ 0.2438351   0.2438351  -0.74731818 -0.74731818 -0.74731818]
 [-1.56117699 -1.56117699 -0.46425312 -0.46425312 -0.46425312]] 
 ##########


In [78]:
# tile 以array整体为单位进行指定倍数扩展
print(arr,'\n ##########')
print(np.tile(arr,2),'\n ##########')
print(np.tile(arr,(2,1)),'\n ##########')
print(np.tile(arr,(3,2)),'\n ##########')

[0 1 2] 
 ##########
[0 1 2 0 1 2] 
 ##########
[[0 1 2]
 [0 1 2]] 
 ##########
[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]] 
 ##########


## 生成特定矩阵

### ones,zeros:0/1矩阵

```python
ones(shape, dtype=float64)
zeros(shape, dtype=float64)
```

产生一个制定形状的全 `0` 或全 `1` 的数组，还可以制定数组类型：

In [56]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones([2,3], dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### empty:空矩阵

    empty(shape, dtype=float64, order='C')

也可以使用 `empty` 方法产生一个制定大小的数组（数组所指向的内存未被初始化，所以值随机），再用 `fill` 方法填充：

In [58]:
a = np.empty(2)
a

array([1.28500842e-311, 0.00000000e+000])

### empty`_`like, ones`_`like, zeros`_`like,identity

    empty_like(a)
    ones_like(a)
    zeros_like(a)

产生一个跟 `a` 大小一样，类型一样的对应数组。

In [59]:
a = np.array([[1,2], [3,4]])

In [60]:
# 生成全是1的矩阵
np.ones_like(a)

array([[1, 1],
       [1, 1]])

In [61]:
# 生成全是0的矩阵
np.zeros_like(a)

array([[0, 0],
       [0, 0]])

In [62]:
# 生成全是空的矩阵
np.empty_like(a)

array([[-1864395872,         605],
       [          0,           0]])

In [ ]:
# 生成单位矩阵
np.identity(4)

## diagonal：对角线元素

In [33]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [34]:
# 查看对角线元素
a.diagonal()

array([11, 22, 33])

可以使用偏移来查看它的次对角线，正数表示右移，负数表示左移：

In [35]:
a.diagonal(offset=1)

array([21, 32])

In [36]:
a.diagonal(offset=-1)

array([12, 23])

## astype:改变数据类型

`NumPy`的数据类型具体如下：

|基本类型|可用的**Numpy**类型|备注
|--|--|--
|布尔型|`bool`|占1个字节
|整型|`int8, int16, int32, int64, int128, int`| `int` 跟**C**语言中的 `long` 一样大
|无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`| `uint` 跟**C**语言中的 `unsigned long` 一样大
|浮点数| `float16, float32, float64, float, longfloat`|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
|复数| `complex64, complex128, complex, longcomplex`| 默认为 `complex128` ，即实部虚部都为双精度
|字符串| `string, unicode` | 可以使用 `dtype=S4` 表示一个4字节字符串的数组
|对象| `object` |数组中可以使用任意值|
|Records| `void` ||
|时间| `datetime64, timedelta64` ||

任意类型的数组：

In [10]:
arr3 = np.array(['2', ' 534'], dtype=np.string_)
arr3.astype(np.int32)

array([  2, 534])

In [11]:
arr2.astype(np.float64)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [12]:
arr1.astype(arr2.dtype)

array([6, 7, 8, 0, 1])

## array之间的运算

In [13]:
arr2 * arr2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [14]:
arr2*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

## 数组广播机制

In [79]:
a = np.array([[ 0, 0, 0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])
b = np.array([0,1,2])

a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

结果一样，虽然两个数组的维数不一样，但是 **Numpy** 检测到 `b` 的维度与 `a` 的维度匹配，所以将 `b` 扩展为之前的形式，得到相同的形状。

对于更高维度，这样的扩展依然有效。 

## 切片与索引

In [3]:
import numpy as np
from numpy.random import randn

***
### 切片

切片在内存中使用的是引用机制。

In [4]:
a = np.array([0,1,2,3,4])
b = a[2:4]
b

array([2, 3])

引用机制意味着，**Python**并没有为 `b` 分配新的空间来存储它的值，而是让 `b` 指向了 `a` 所分配的内存空间，因此，改变 `b` 会改变 `a` 的值：

In [5]:
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

而这种现象在列表中并不会出现：

In [11]:
a = [1,2,3,4,5]
b = a[2:3]
c = 111
b[0] = 13234
print('\n',b,
      '\n',a)


 [13234] 
 [1, 2, 3, 4, 5]


这样做的好处在于，对于很大的数组，不用大量复制多余的值，节约了空间。

缺点在于，可能出现改变一个值改变另一个值的情况。

一个解决方法是使用`copy()`方法产生一个复制，这个复制会申请新的内存：

In [10]:
a = np.array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
a

array([0, 1, 2, 3, 4])

***
### 索引

In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
data[(names == 'Bob') | (names == 'Joe')]

array([[-1.21907528,  1.2705255 , -0.54212363,  0.80974703],
       [-1.76553628, -1.80329136, -0.90210562, -0.74221657],
       [ 2.28587489,  0.30085764, -0.95233408, -1.54211855],
       [ 0.79052931, -1.37344705,  1.51744052, -0.18722192],
       [-0.25895972,  0.30646545, -0.03690562, -0.88666348]])

In [18]:
#利用整数数组进行索引
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [23]:
# 将数组各元素的小数和整数部分以两个独立数组形式返回
arr = randn(7)*5
print(arr)
np.modf(arr)

[ 0.62653967  8.36582088 -4.735825    1.11698705  3.08388594 -3.18673245
 -0.17518684]


(array([ 0.62653967,  0.36582088, -0.735825  ,  0.11698705,  0.08388594,
        -0.18673245, -0.17518684]), array([ 0.,  8., -4.,  1.,  3., -3., -0.]))

In [70]:
# bool索引
bools = np.array([1,0,1,0,0])
print(bools.any(), bools.all())

True False


In [26]:
# array比较
np.array([1,2,3])<np.array([4,5,6])

array([ True,  True,  True])

## np.where:筛选

In [29]:
# 满足条件(condition)，输出x，不满足输出y
xarr = np.array([i/10.0 for i in range(11,16)])
yarr = np.array([i/10.0 for i in range(21,26)])
cond = np.array([1, 0, 1, 1, 0])
result = np.where(cond, xarr, yarr)
print(xarr)
print(yarr)
print(result)

# np.where(condition)只有条件 (condition)，没有x和y，则输出满足条件 (即非0) 元素的坐标
a = np.array([2,4,6,8,10])
print(np.where(a > 5))

[1.1 1.2 1.3 1.4 1.5]
[2.1 2.2 2.3 2.4 2.5]
[1.1 2.2 1.3 1.4 2.5]
(array([2, 3, 4], dtype=int64),)


In [31]:
arr = randn(4,4)
arr

array([[ 1.18029014,  0.71319241,  2.01895214,  1.37924678],
       [ 0.12525128, -1.81354103,  0.38562474, -0.16819841],
       [ 1.47071074, -0.26982163, -1.11628426,  0.35210247],
       [ 0.48588561, -1.32807385, -1.33038652,  0.5009419 ]])

In [33]:
# 赋固定数字
np.where(arr>0, 2, arr)

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.81354103,  2.        , -0.16819841],
       [ 2.        , -0.26982163, -1.11628426,  2.        ],
       [ 2.        , -1.32807385, -1.33038652,  2.        ]])

In [30]:
# 可以嵌套使用
cond1 = np.array([1, 0, 1])
cond2 = np.array([0, 0,1])
np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2,3)))

array([1, 3, 0])

## choose 函数实现条件筛选

对于数组，我们有时候需要进行类似 `switch` 和 `case` 进行条件选择，此时使用 choose 函数十分方便：

In [75]:
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

np.choose(control, [10, 11, 12])

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

在上面的例子中，`choose` 将 `0,1,2` 对应的值映射为了 `10, 11, 12`，这里的 `0,1,2` 表示对应的下标。

事实上， `choose` 不仅仅能接受下标参数，还可以接受下标所在的位置：

In [76]:
i0 = np.array([[0,1,2],
               [3,4,5],
               [6,7,8]])
i2 = np.array([[20,21,22],
               [23,24,25],
               [26,27,28]])
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

np.choose(control, [i0, 10, i2])

array([[10,  1, 10],
       [23, 10,  5],
       [10, 27, 28]])

这里：

1. `control` 传入第一个 `1` 对应的是`[i0, 10, i2]`的下标为`1`的元素 10；

2. 传入的第一个 `0` 对应于 `i0` 相应位置的值即 `1`，剩下的以此类推。 

下面的例子将数组中所有小于 10 的值变成了 10，大于 15 的值变成了 15。

In [78]:
a = np.array([[ 0, 1, 2], 
              [10,11,12], 
              [20,21,22]])

lt = a < 10
gt = a > 15

choice = lt + 2 * gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

## 对于单个array的各种计算

In [35]:
# 给出array的各种统计值
arr = np.array([[1,1,1,1], [3,3,3,3]])
print(arr.mean(axis=1), np.mean(arr,axis=0), arr.var(), arr.max(), arr.min(), arr.argmin(), arr.cumsum(), arr.cumprod())
print((randn(100)>0).sum())

[1. 3.] [2. 2. 2. 2.] 1.0 3 1 0 [ 1  2  3  4  7 10 13 16] [ 1  1  1  1  3  9 27 81]
57


In [13]:
# 将数值限制在某个范围：
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## reduce 方法

In [71]:
# reduce方法
a = np.array([1,2,3,4])

np.add.reduce(a)

10

In [72]:
a = np.array([[1,2,3],[4,5,6]])

np.add.reduce(a,1)

array([ 6, 15])

In [73]:
# 作用于字符串

a = np.array(['ab', 'cd', 'ef'], np.object)

np.add.reduce(a)

'abcdef'

## sort 和 argsort 方法

In [16]:
# 排序
arr = randn(5,3)
arr

array([[-0.23451556,  1.35552101,  2.85991733],
       [-0.09183913,  0.96851984,  0.5120501 ],
       [-0.52065659, -1.41860519, -0.6794761 ],
       [ 0.24423661,  0.13993375, -0.19656932],
       [-1.51819783, -0.88074602,  0.46748557]])

In [17]:
# axis：数组排序时的基准，axis=0 按列排列；axis=1 按行排列
arr1 = np.sort(arr, axis=0)
print(arr)
print('排序之后的结果是\n',arr1)

[[-0.23451556  1.35552101  2.85991733]
 [-0.09183913  0.96851984  0.5120501 ]
 [-0.52065659 -1.41860519 -0.6794761 ]
 [ 0.24423661  0.13993375 -0.19656932]
 [-1.51819783 -0.88074602  0.46748557]]
排序之后的结果是
 [[-1.51819783 -1.41860519 -0.6794761 ]
 [-0.52065659 -0.88074602 -0.19656932]
 [-0.23451556  0.13993375  0.46748557]
 [-0.09183913  0.96851984  0.5120501 ]
 [ 0.24423661  1.35552101  2.85991733]]


In [18]:
# sort除了可以看做np的函数，也可以看成array的属性之一
arr.sort(axis=0)
arr

array([[-1.51819783, -1.41860519, -0.6794761 ],
       [-0.52065659, -0.88074602, -0.19656932],
       [-0.23451556,  0.13993375,  0.46748557],
       [-0.09183913,  0.96851984,  0.5120501 ],
       [ 0.24423661,  1.35552101,  2.85991733]])

`argsort` 返回从小到大的排列在数组中的索引位置：

In [21]:
arr1 = np.argsort(arr, axis=1)
print('排序之后的指标结果是\n',arr1)

排序之后的指标结果是
 [[0 1 2]
 [1 0 2]
 [0 1 2]
 [0 2 1]
 [0 1 2]]


## searchsorted 函数

    searchsorted(sorted_array, values)

`searchsorted` 接受两个参数，其中，第一个必需是已排序的数组。

In [24]:
sorted_array = np.linspace(0,1,5)
values = np.array([.1,.8,.3,.12,.5,.25])
np.searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

排序数组：

|0|1|2|3|4|
|-|-|-|-|-|
|0.0|0.25|0.5|0.75|1.0

数值：

|值|0.1|0.8|0.3|0.12|0.5|0.25|
|-|-|-|-|-|-|-|
|插入位置|1|4|2|1|2|1|

`searchsorted` 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 `0.1` 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 `1` 处，故第一个返回值为 `1`。

## arange函数：类似range

`arange` 类似于**Python**中的 `range` 函数，只不过返回的不是列表，而是数组：

    arange(start, stop=None, step=1, dtype=None)

产生一个在区间 `[start, stop)` 之间，以 `step` 为间隔的数组，如果只输入一个参数，则默认从 `0` 开始，并以这个值为结束：

In [39]:
import numpy as np
np.arange(4)

array([0, 1, 2, 3])

与 `range` 不同， `arange` 允许非整数值输入，产生一个非整型的数组：

In [40]:
np.arange(0, 2 * np.pi, np.pi / 4)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

## linspace, logspace：等距分布

    linspace(start, stop, N)

产生 `N` 个等距分布在 `[start, stop]`间的元素组成的数组，包括 `start, stop`。

    logspace(start, stop, N)

产生 N 个对数等距分布的数组，默认以10为底：

In [42]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

## meshgrid:等距网络

In [46]:
x_ticks = np.linspace(-1, 1, 5)
y_ticks = np.linspace(-1, 1, 5)

x, y = np.meshgrid(x_ticks, y_ticks)

`x` 对应网格的第一维，`y` 对应网格的第二维。

这里产生的 `x, y`如下：

In [47]:
x

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])

In [48]:
y

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

## r`_` , c`_`:行向量/列向量

我们可以使用 `r_ / c_` 来产生行向量或者列向量。

使用切片产生：

In [50]:
np.r_[0:1:0.1]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

连接多个序列，产生数组：

In [51]:
np.r_[(3,22,11), 4.0, [15, 6]]

array([ 3., 22., 11.,  4., 15.,  6.])

In [52]:
# 列向量
np.c_[1:3:5j]

array([[1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ]])

## numpy的交并补

子集：[np.in1d](http://doc.codingdict.com/NumPy_v111/reference/generated/numpy.in1d.html)

In [45]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [46]:
# 交集
np.intersect1d(values, [2,3,6])

array([2, 3, 6])

## 生成各种概率分布

In [49]:
samples = np.random.normal(size=(4,4))
samples

array([[ 0.72839955, -0.17624434,  0.52071077,  0.66522577],
       [ 0.90677079, -0.84590989, -0.76505035, -1.16936409],
       [-0.67207943, -0.90062313, -0.95062222, -0.12348399],
       [ 1.52615952,  1.40666646,  1.61997447,  0.01507119]])

In [50]:
import random
np.random.seed(0)
print(np.random.rand(4))
np.random.seed(0)
print(np.random.rand(3))
print(np.random.permutation(np.arange(10)))
arr = np.array([12,3,4])
np.random.shuffle(arr)
print(arr)
print(np.random.randint(0,2, size=[2,2]))
print(np.random.randn(3,4))
print(np.random.binomial(0.4,0.6, size=[2,3]))
print(np.random.normal(size=(3,4)))
print(np.random.beta(3,4, size=[2,2]))

[0.5488135  0.71518937 0.60276338 0.54488318]
[0.5488135  0.71518937 0.60276338]
[8 6 4 0 2 5 9 1 7 3]
[ 3  4 12]
[[0 1]
 [0 1]]
[[ 2.54520078  1.08081191  0.48431215  0.57914048]
 [-0.18158257  1.41020463 -0.37447169  0.27519832]
 [-0.96075461  0.37692697  0.03343893  0.68056724]]
[[0 0 0]
 [0 0 0]]
[[ 1.46274045  1.53502913  0.56644004  0.14926509]
 [-1.078278    1.39547227  1.78748405 -0.56951726]
 [ 0.17538653 -0.46250554 -1.0858006   0.63973599]]
[[0.4677088  0.46166706]
 [0.62560303 0.38300476]]


## mat,bmat:矩阵转换

使用 `mat` 方法将 `2` 维数组转化为矩阵：

In [63]:
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

也可以使用 **Matlab** 的语法传入一个字符串来生成矩阵：

In [64]:
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [65]:
# 利用分块创造新的矩阵：
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [66]:
# 矩阵与向量的乘法：
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [67]:
A * x

matrix([[17],
        [21],
        [50]])

## 比较和逻辑运算

运算|函数<
--- | --- 
`==` | `equal`
`!=` | `not_equal`
`>` | `greater`
`>=` | `greater_equal`
`<` | `less`
`<=` | `less_equal`
| `logical_and`
| `logical_or`
| `logical_xor`
| `logical_not`
`&` | `bitwise_and`
 | `bitwise_or`
`^` | `bitwise_xor`
`~` | `invert`
`>>` | `right_shift`
`<<` | `left_shift`

要注意的是 `&` 的运算优先于比较运算如 `>` 等，所以必要时候需要加上括号：

In [68]:
a = np.array([1,2,4,8])
b = np.array([16,32,64,128])

(a > 3) & (b < 100)

array([False, False,  True, False])

In [69]:
a = np.array([0,1,2])
b = np.array([0,10,0])

np.logical_and(a, b)

array([False,  True, False])

## 方法总结

||作用|
|-|-|
|1|**基本属性**
|`a.dtype`|数组元素类型 `float32,uint8,...`
|`a.shape`|数组形状 `(m,n,o,...)`
|`a.size`|数组元素数
|`a.itemsize`|每个元素占字节数
|`a.nbytes`|所有元素占的字节
|`a.ndim`|数组维度
|2|**形状相关**
|`a.flat`|所有元素的迭代器
|`a.flatten()`|返回一个1维数组的复制
|`a.ravel()`|返回一个1维数组，高效
|`a.resize(new_size)`|改变形状
|`a.swapaxes(axis1, axis2)`|交换两个维度的位置
|`a.transpose(*axex)`|交换所有维度的位置
|`a.T`|转置，`a.transpose()`
|`a.squeeze()`| 去除所有长度为1的维度
|3|**填充复制**
|`a.copy()`| 返回数组的一个复制
|`a.fill(value)`| 将数组的元组设置为特定值
|4|**转化**
|`a.tolist()`|将数组转化为列表
|`a.tostring()`|转换为字符串
|`a.astype(dtype)`|转化为指定类型
|`a.byteswap(False)`|转换大小字节序
|`a.view(type_or_dtype)`|生成一个使用相同内存，但使用不同的表示方法的数组
|5|**复数**
|`a.imag`|虚部
|`a.real`|实部
|`a.conjugate()`|复共轭
|`a.conj()`|复共轭（缩写）
|6|**保存**
|`a.dump(file)`|将二进制数据存在file中
|`a.dump()`|将二进制数据表示成字符串
|`a.tofile(fid, sep="",format="%s")`|格式化ASCⅡ码写入文件
|7|**查找排序**
|`a.nonzero()`|返回所有非零元素的索引
|`a.sort(axis=-1)`|沿某个轴排序
|`a.argsort(axis=-1)`|沿某个轴，返回按排序的索引
|`a.searchsorted(b)`|返回将b中元素插入a后能保持有序的索引值
|8|**元素数学操作**
|`a.clip(low, high)`|将数值限制在一定范围内
|`a.round(decimals=0)`|近似到指定精度
|`a.cumsum(axis=None)`|累加和
|`a.cumprod(axis=None)`|累乘积
|9|**约简操作**
|`a.sum(axis=None)`|求和
|`a.prod(axis=None)`|求积
|`a.min(axis=None)`|最小值
|`a.max(axis=None)`|最大值
|`a.argmin(axis=None)`|最小值索引
|`a.argmax(axis=None)`|最大值索引
|`a.ptp(axis=None)`|最大值减最小值
|`a.mean(axis=None)`|平均值
|`a.std(axis=None)`|标准差
|`a.var(axis=None)`|方差
|`a.any(axis=None)`|只要有一个不为0，返回真，逻辑或
|`a.all(axis=None)`|所有都不为0，返回真，逻辑与